// Generated by gencpp from file vicon/SetPose.msg
// DO NOT EDIT!


#ifndef VICON_MESSAGE_SETPOSE_H
#define VICON_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <vicon/SetPoseRequest.h>
#include <vicon/SetPoseResponse.h>


namespace vicon
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace vicon


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vicon::SetPose > {
  static const char* value()
  {
    return "9073f079ef6a99118cd85a569b78a1cb";
  }

  static const char* value(const ::vicon::SetPose&) { return value(); }
};

template<>
struct DataType< ::vicon::SetPose > {
  static const char* value()
  {
    return "vicon/SetPose";
  }

  static const char* value(const ::vicon::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::vicon::SetPoseRequest> should match 
// service_traits::MD5Sum< ::vicon::SetPose > 
template<>
struct MD5Sum< ::vicon::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vicon::SetPose >::value();
  }
  static const char* value(const ::vicon::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vicon::SetPoseRequest> should match 
// service_traits::DataType< ::vicon::SetPose > 
template<>
struct DataType< ::vicon::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::vicon::SetPose >::value();
  }
  static const char* value(const ::vicon::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vicon::SetPoseResponse> should match 
// service_traits::MD5Sum< ::vicon::SetPose > 
template<>
struct MD5Sum< ::vicon::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vicon::SetPose >::value();
  }
  static const char* value(const ::vicon::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vicon::SetPoseResponse> should match 
// service_traits::DataType< ::vicon::SetPose > 
template<>
struct DataType< ::vicon::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::vicon::SetPose >::value();
  }
  static const char* value(const ::vicon::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VICON_MESSAGE_SETPOSE_H
